version: "3.9"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./static:/app/static  # ✅ добавь это, чтобы index.html был доступен

volumes:
  pgdata:
